### PR TITLE
Automatically restore avatar & bio

### PR DESCRIPTION
**Pull request by wnelson03**
Automatically restore avatar & bio

I refuse to buy nitro so I don't know JSON param for banner, though I'm sure you could find it and add that into the code as well.

### CODE REVIEW

**Comment by itschasa** [comment]
the reason i refrained from doing profile stuff automatically is because it can lead to phone locks if the account is somewhat flagged. id prefer to keep this feature not added to help people not get locks. thanks for the pr tho, if you disagree feel free to reply

**Comment by wnelson03** [comment]
> the reason i refrained from doing profile stuff automatically is because it can lead to phone locks if the account is somewhat flagged. id prefer to keep this feature not added to help people not get locks. thanks for the pr tho, if you disagree feel free to reply

Has a phone lock occurred from this before? If not I believe it should be considered. I don't see how this could be any more suspicious to Discord than all the other actions this selfbot does.

**Comment by itschasa** [comment]
if it's a brand new account (which lets be real, 90% of people that are going to be restoring their account onto a new account), the chance of you getting locked are a lot higher,  because of the different fingerprints on registration, compared to the restore tool.

using an account which is 12-36 hours would more likely not lock the account, but people are impatient and want to restore instantly.

**Comment by wnelson03** [comment]
> if it's a brand new account (which lets be real, 90% of people that are going to be restoring their account onto a new account), the chance of you getting locked are a lot higher, because of the different fingerprints on registration, compared to the restore tool.
> 
> using an account which is 12-36 hours would more likely not lock the account, but people are impatient and want to restore instantly.

Can this be mitigated by being phone verified? If so, I believe you should add setting where people can select to automatically restore profile or manually, or, if you’re able to automatically detect whether an account is phone verified (which I’m pretty sure is possible, I’ve seen in other Discord-related software I’ve used), you could automatically update profile if phone verified, or manually save files and show message saying phone not verified so details saved manually. Also, it’s kind of odd that the server invites and dm history is sent in that server this bot creates, yet the profile bio and profile pic are saved to local computer. It would probably be better if profile bio and profile avatar was sent in server.

Anyways, your call, I’m not too familiar with selfbots so you know better. Great selfbot, I’ve used this twice so far and love it.

**Comment by wnelson03** [comment]
Most people I know who have to create accounts frequently are required to phone verify, regardless of whether they use a selfbot.

I typically use https://5sim.net as it's cheap and my real phone number is a VOIP one so it's not accepted.

**Comment by itschasa** [comment]
> Can this be mitigated by being phone verified?

somewhat, but the thing that really matters is age and headers consistency. with phone verification, theres still a chance of being 
termed, if your requests also look not legit.


> Also, it’s kind of odd that the server invites and dm history is sent in that server this bot creates, yet the profile bio and profile pic are saved to local computer. It would probably be better if profile bio and profile avatar was sent in server.

i agree with you there, ill add that soon.


> Most people I know who have to create accounts frequently are required to phone verify, regardless of whether they use a selfbot.

they've obviously been doing too much registering on discord recently, or have just been terminated on discord.


> I believe you should add setting where people can select to automatically restore profile or manually,

potentially, but with a warning to let the user know that they could get locked/termed.

**Pull request closed without merging**
