### PR TITLE
Update client_info.py

### PR DESCRIPTION
**Pull request by Cloudzik1337**
#29 As mentioned here
idk why i did pr never did and wanted to so ur job easier :*

### CODE REVIEW

**Comment by itschasa** [comment]
did you test this?

**Comment by Cloudzik1337** [comment]
`print("Build Num ==", int(build_nums[0]))` 
`>>> Build Num == 254206`

**Comment by infamouskoala** [comment]
this is useless, i dont think there are any breaks in the tool without this either

**Comment by Cloudzik1337** [comment]
Traceback (most recent call last):  line 29, in get_client_build_number
    build_url = 'https://discord.com/assets/' + re.compile(r'assets/+([a-z0-9]+)\.js').findall(login_page)[-2] + '.js' .................~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
Failed to get build number from Discord, failing back to hardcoded value...

**Comment by infamouskoala** [comment]
works well on my machine, skill issue buddy

**Comment by Cloudzik1337** [comment]
Indian server issue

**Comment by infamouskoala** [comment]
did u fr call me indian??? >:( ur done lil bro

**Comment by Cloudzik1337** [comment]
nope only servers u connect to

**Pull request merged**
